### ISSUE TITLE
Can I get a country classification?

### ISSUE THREAD

**Issue by mwouts** [OliverSherouse/wbdata#22]
Hi, thanks for the nice package.

I'm trying to plot total population per continent, or a similar classification.
Is it possible to get a country classification using `wbdata`? When I download a file manually from the world bank, I get some country metadata (with region information, no continent though). Can I access that metadata using `wbdata` ?

Thanks

**Comment by OliverSherouse** [comment]
I don't think you can get continent directly, because I don't think the World Bank gets in the business of defining continents. You can get results for a region by passing the code for the region in the `country` argument.

**Comment by mwouts** [comment]
Thanks @OliverSherouse for your answer. Yes, when I asked I was not aware... `country` not only contains countries, but also `"World"`, and a series of regions as you mention. Precisely, I found that the following [zones](https://github.com/mwouts/jupytext/blob/9ca0d5298c7e66de8b0bbcd5522a12ebca80aa0e/demo/World%20population.py#L62-L67) have a population total equal to the one in `"World"`:
```
'North America', 'Middle East & North Africa', 'Latin America & Caribbean',
'Europe & Central Asia', 'Sub-Saharan Africa', 'South Asia', 'East Asia & Pacific'
```
