### ISSUE TITLE
get_dataframe documentation refers to absent pandas argument

### ISSUE THREAD

**Issue by MaxGhenis** [OliverSherouse/wbdata#27]
The documentation for `get_dataframe`'s `keep_levels` argument refers to "if...pandas is True" but there's no `pandas` argument in the function.

![image](https://user-images.githubusercontent.com/6076111/53686522-ef7e1500-3cdc-11e9-9ae6-eff2a4e6060d.png)

https://github.com/OliverSherouse/wbdata/blob/0541f6da9d1d867ce58badfb96d6648c754fe2aa/wbdata/api.py#L394-L395

**Comment by OliverSherouse** [comment]
Fixed in Dev.
