### ISSUE TITLE
get_country(incomelevel="OEC") produces "IndexError: list index out of range" error

### ISSUE THREAD

**Issue by MaxGhenis** [OliverSherouse/wbdata#28]
The [readthedocs documentation](https://wbdata.readthedocs.io/en/latest/) includes this line:

    countries = [i['id'] for i in wbdata.get_country(incomelevel="OEC", display=False)]

This returns the error:
>IndexError: list index out of range

The same error is returned with the simpler:

    wbdata.get_country(incomelevel="OEC")

And other `incomelevel` values like `oec`, `OECD`, and `oecd` also produce this error.

`get_country()` without the `incomelevel` argument works fine.

Function documentation doesn't include more information like a list of valid `incomelevel` values:
https://github.com/OliverSherouse/wbdata/blob/0541f6da9d1d867ce58badfb96d6648c754fe2aa/wbdata/api.py#L253-L261

**Comment by MaxGhenis** [comment]
`wbdata.get_incomelevel()` shows that some `incomelevel` values are gone, including `OEC`:
![image](https://user-images.githubusercontent.com/6076111/53687009-c3b25d80-3ce3-11e9-9a6e-223628c52f37.png)

I'll make a PR replacing the example with `HIC`.

**Comment by MaxGhenis** [comment]
Proposed in https://github.com/OliverSherouse/wbdata/pull/30.

**Comment by OliverSherouse** [comment]
Thanks for the fix.
