### ISSUE TITLE
Comparison to pandas-datareader World Bank data

### ISSUE THREAD

**Issue by MaxGhenis** [OliverSherouse/wbdata#32]
After discovering `wbdata` today, I just discovered the [`pandas_datareader` package](https://github.com/pydata/pandas-datareader), which [includes World Bank data support](https://pydata.github.io/pandas-datareader/stable/remote_data.html#world-bank) and is developed under [pydata](https://github.com/pydata) (it apparently used to be part of `pandas` itself). It looks to have similar functionality as `wbdata`, but I've only used it a bit. Thought it'd be good to be aware of.

I filed a parallel issue there at https://github.com/pydata/pandas-datareader/issues/624.

**Comment by OliverSherouse** [comment]
Yes, I was aware of this functionality in `pandas-datareader`, and in fact, I at one point had this project labeled as superseded. But the functionality and style is slightly different, and for whatever reason people seem to like this library, so I'll keep it rolling while I feel like that's the case.
