### ISSUE TITLE
Quarterly External Debt Statistics (SDDS) Value error

### ISSUE THREAD

**Issue by wochner** [OliverSherouse/wbdata#7]
I receive a value error when querying for some of the SDDS External debt data.

indicators = {'DT.DOD.DECT.CD.AR.US': 'Gross external debt'}                         
df = wbdata.get_dataframe(indicators, convert_date=False)

Traceback (most recent call last):
  File "F:\source\Python\macro\source_external_debt.py", line 36, in <module>
    df = wbdata.get_dataframe(indicators, convert_date=False) # load data from worldbank
  File "<decorator-gen-3>", line 2, in get_dataframe
  File "C:\Python27\lib\site-packages\wbdata\api.py", line 53, in uses_pandas
    return f(*args, **kwargs)
  File "C:\Python27\lib\site-packages\wbdata\api.py", line 416, in get_dataframe
    for i in indicators}
  File "C:\Python27\lib\site-packages\wbdata\api.py", line 416, in <dictcomp>
    for i in indicators}
  File "C:\Python27\lib\site-packages\wbdata\api.py", line 167, in get_data
    data = fetcher.fetch(query_url, args)
  File "C:\Python27\lib\site-packages\wbdata\fetcher.py", line 163, in fetch
    raw_response = fetch_url(query_url)
  File "C:\Python27\lib\site-packages\wbdata\fetcher.py", line 135, in fetch_url
    raise ValueError
ValueError

Other fields (that are very similar) work fine, for example: {'DT.DOD.DECT.CD.GG.AR.US': 'Gross external debt general government'}

**Comment by OliverSherouse** [comment]
Thanks for this report; I'll investigate.

**Comment by wochner** [comment]
Hi Oliver,

Thanks for looking into this.

In your other email you also mentioned that I should highlight feature requests. I am relatively new to GitHub. Is there a place for that. Having the IMF API included would be tremendous as both organizations have similar data. As I am also new to python, I have no idea how much effort such an implementation takes. Would also be glad to help, but it will take some time and experience until I am there.

Cheers,
Mike

**Comment by wochner** [comment]
I have done some more research and looked at Table 2 of the QEDS, because it is rather short. [here](http://datatopics.worldbank.org/debt/qeds) is a good overview of all the tables. 

Most of the data fields on this Table 2 also raise the same ValueError as above:

DT.DOD.DECT.CD.FC.US (0071_T2_Foreign currency 5/)
DT.DOD.DSTC.CD.FC.US (0072_T2_.. Short-term)
DT.DOD.DLXF.CD.FC.US (0073_T2_.. Long-term 6/)
DT.DOD.DECT.CD.DC.US (0074_T2_Domestic currency 7/)
DT.DOD.DSTC.CD.DC.US (0075_T2_.. Short-term)
DT.DOD.DLXF.CD.DC.US (0076_T2_.. Long-term)
DT.DOD.DECT.CD.UC.US (0077_T2_Unallocated)

Interstingly, the last field and sumtotal of that table works fine:

DT.DOD.DECT.CD.DT.US (0078_T2_Gross External Debt Position)

Even more confusing, as this field should contain the same value as the field DT.DOD.DECT.CD.GG.AR.US (0059_T1_Gross External Debt Position), which I have reported in the original post that does raise a ValueError.

**Comment by OliverSherouse** [comment]
This seems to be fixed with the switch to the requests backend. Per your question about the IMF, I'll take a look at that as a project for a different library, but I don't know that it makes sense to add it to this _particular_ library.
